version: '3'
services:
  app:
    container_name: struct_web_app
    image: struct_web_app
    build: .
    networks:
      - main_network
    ports:
      - "3005:3005"
    volumes:
      - .:/app
      - /app/node_modules

  database:
    container_name: database
    image: mongo
    volumes:
      - /data/db/mongo
    ports:
      - "27017:27017"
    networks:
      - main_network
volumes:
  node_modules:

networks:
  main_network:
    driver: bridge